export { Header } from "./Header";
export { Hero } from "./Hero";
export { About } from "./About";
export { TechStack } from "./TechStack";
export { GitHubActivity } from "./GitHubActivity";
export { Projects } from "./Projects";
export { Differentiators } from "./Differentiators";
export { Contact } from "./Contact";
export { Footer } from "./Footer";
